name = "my-app"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

# The directory where Cloudflare Pages expects the build output.
pages_build_output_dir = ".vercel/output/static"
